### ISSUE TITLE
Won't build - self reference.

### ISSUE THREAD

**Issue by bradintheusa** [josip2312/typescript-lib-vite#1]
Hi

How do I build this, it seems to reference itself
```
"my-component-lib": "my-component-lib-0.0.0.tgz",
```

**Comment by josip2312** [comment]
The self-referencing dependency was added just as an example, you would need to adjust this to your needs
https://jivancic.com/posts/build-a-component-library.html

**Comment by bradintheusa** [comment]
Thanks
